export { default as TimeSection } from './TimeSection'
export { default as WeatherSection } from './WeatherSection'
export { default as NewsSection } from './NewsSection'
export { default as CurrencySection } from './CurrencySection'
export { default as SearchSection } from './SearchSection'
export { default as RadioSection } from './RadioSection'
export { default as VideosSection } from './VideosSection'
export { default as NoticesSection } from './NoticesSection'
export { default as JobsSection } from './JobsSection'
export { default as EducationSection } from './EducationSection'
export { default as AIAssistantSection } from './AIAssistantSection'
export { default as MarketSection } from './MarketSection'

// New widgets
export { default as PrayerTimesSection } from './PrayerTimesSection'
export { default as CricketSection } from './CricketSection'
export { default as CommoditySection } from './CommoditySection'
export { default as EmergencySection } from './EmergencySection'
export { default as HolidaysSection } from './HolidaysSection'
export { default as FeedbackNotice } from './FeedbackNotice'
export { default as AppDirectory } from './AppDirectory'
